CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  provider VARCHAR(16) NOT NULL,
  external_subject VARCHAR(512),
  display_name VARCHAR(255),
  email VARCHAR(320),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT users_provider_check CHECK (provider IN ('local', 'ldap', 'oidc')),
  CONSTRAINT users_external_identity_unique UNIQUE (provider, external_subject)
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(1000),
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_domain_grants (
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  domain VARCHAR(255) NOT NULL,
  permission VARCHAR(16) NOT NULL,
  PRIMARY KEY (role_id, domain, permission),
  CONSTRAINT role_domain_permission_check CHECK (permission IN ('READ', 'QUERY', 'WRITE'))
);

CREATE TABLE role_capabilities (
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  capability VARCHAR(64) NOT NULL,
  PRIMARY KEY (role_id, capability),
  CONSTRAINT role_capability_check
    CHECK (capability IN ('VIEW_COMPILED_SQL', 'VIEW_PHYSICAL_LINEAGE'))
);

CREATE TABLE service_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  api_key_hash VARCHAR(255) NOT NULL,
  role_id BIGINT NOT NULL REFERENCES roles(id),
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  revoked_at TIMESTAMP WITH TIME ZONE,
  replaced_by BIGINT REFERENCES refresh_tokens(id)
);

CREATE INDEX refresh_tokens_user_idx ON refresh_tokens(user_id);
