package com.acme.semantic.core;

public enum SemanticErrorCode {
  INVALID_TOOL_ARGUMENTS,
  SEMANTIC_OBJECT_NOT_FOUND,
  INVALID_SEMANTIC_QUERY,
  INCOMPATIBLE_METRICS_AND_DIMENSIONS,
  AMBIGUOUS_JOIN_PATH,
  ACCESS_DENIED,
  QUERY_LIMIT_EXCEEDED,
  COMPILATION_FAILURE,
  EXECUTION_TIMEOUT,
  EXECUTION_FAILURE,
  HIGH_CARDINALITY_SEARCH_REQUIRED
}
