import {useEffect,useState,type FormEvent} from 'react';
import {ApiError,api} from './api';

type RoleSummary={id:number;name:string;admin:boolean};
type AdminUser={id:number;username:string;provider:string;displayName?:string;email?:string;enabled:boolean;mustChangePassword:boolean;createdAt:string;updatedAt:string;roles:RoleSummary[]};
type Permission='READ'|'QUERY'|'WRITE';
type Capability='VIEW_COMPILED_SQL'|'VIEW_PHYSICAL_LINEAGE';
type DomainGrant={domain:string;permissions:Permission[]};
type Role={id:number;name:string;description?:string;admin:boolean;grants:DomainGrant[];capabilities:Capability[]};
type ServiceAccount={id:number;name:string;enabled:boolean;requiresRotation:boolean;role:RoleSummary};
type ServiceSecret={serviceAccount:ServiceAccount;apiKey:string};
type Tab='users'|'roles'|'service-accounts';

export default function AdminPage(){
  const[tab,setTab]=useState<Tab>('users'),[users,setUsers]=useState<AdminUser[]>([]),[roles,setRoles]=useState<Role[]>([]),[accounts,setAccounts]=useState<ServiceAccount[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[forbidden,setForbidden]=useState(false),[secret,setSecret]=useState<ServiceSecret>();
  const load=async()=>{setLoading(true);try{const[u,r,s]=await Promise.all([api<AdminUser[]>('/admin/users'),api<Role[]>('/admin/roles'),api<ServiceAccount[]>('/admin/service-accounts')]);setUsers(u);setRoles(r);setAccounts(s);setError('');setForbidden(false)}catch(error){setForbidden(error instanceof ApiError&&error.status===403);setError(message(error))}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  if(forbidden)return <AdminState title="Administrator access required" body="You are not permitted to manage Witness identities."/>;
  return <><header className="page-header"><div><div className="eyebrow">Administration</div><h1>Identity and access</h1><p>Manage users, domain grants, capabilities, and service credentials.</p></div></header>{error&&<div className="alert error" role="alert"><strong>{error}</strong></div>}{secret&&<SecretNotice secret={secret} onClose={()=>setSecret(undefined)}/>}<nav className="tabs admin-tabs" aria-label="Administration sections">{(['users','roles','service-accounts'] as Tab[]).map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value.replace('-',' ')}</button>)}</nav>{loading?<AdminState title="Loading administration" body="Resolving current identity configuration…"/>:tab==='users'?<Users users={users} roles={roles} changed={load} failed={setError}/>:tab==='roles'?<Roles roles={roles} changed={load} failed={setError}/>:<ServiceAccounts accounts={accounts} roles={roles} changed={load} failed={setError} reveal={setSecret}/>}</>;
}

function Users({users,roles,changed,failed}:{users:AdminUser[];roles:Role[];changed:()=>Promise<void>;failed:(value:string)=>void}){
  const[username,setUsername]=useState(''),[password,setPassword]=useState(''),[displayName,setDisplayName]=useState(''),[email,setEmail]=useState(''),[roleIds,setRoleIds]=useState<number[]>([]),[busy,setBusy]=useState(false);
  const create=async(event:FormEvent)=>{event.preventDefault();setBusy(true);failed('');try{const user=await api<AdminUser>('/admin/users',{method:'POST',body:JSON.stringify({username,password,displayName,email})});if(roleIds.length)await api('/admin/users/'+user.id+'/roles',{method:'PUT',body:JSON.stringify({roleIds})});setUsername('');setPassword('');setDisplayName('');setEmail('');setRoleIds([]);await changed()}catch(error){failed(message(error))}finally{setBusy(false)}};
  return <div className="admin-stack"><form className="panel admin-create" onSubmit={create}><div className="panel-title"><h2>Create local user</h2></div><div className="admin-form-grid"><label>Username<input required value={username} onChange={event=>setUsername(event.target.value)}/></label><label>Temporary password<input required minLength={8} type="password" value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Display name<input value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label></div><RoleChecks roles={roles} selected={roleIds} onChange={setRoleIds}/><div className="form-actions"><button className="button primary" disabled={busy}>{busy?'Creating…':'Create user'}</button></div></form><section className="admin-list">{users.map(user=><UserEditor key={user.id} user={user} roles={roles} changed={changed} failed={failed}/>)}</section></div>;
}

function UserEditor({user,roles,changed,failed}:{user:AdminUser;roles:Role[];changed:()=>Promise<void>;failed:(value:string)=>void}){
  const[displayName,setDisplayName]=useState(user.displayName||''),[email,setEmail]=useState(user.email||''),[enabled,setEnabled]=useState(user.enabled),[roleIds,setRoleIds]=useState(user.roles.map(role=>role.id)),[busy,setBusy]=useState(false);
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);failed('');try{await action();await changed()}catch(error){failed(message(error))}finally{setBusy(false)}};
  const save=()=>run(async()=>{await api('/admin/users/'+user.id,{method:'PUT',body:JSON.stringify({displayName,email,enabled})});await api('/admin/users/'+user.id+'/roles',{method:'PUT',body:JSON.stringify({roleIds})})});
  const reset=()=>{const next=window.prompt('New temporary password (at least 8 characters)');if(next)void run(()=>api('/admin/users/'+user.id+'/password',{method:'POST',body:JSON.stringify({newPassword:next})}))};
  const remove=()=>{if(window.confirm('Delete user '+user.username+'?'))void run(()=>api('/admin/users/'+user.id,{method:'DELETE'}))};
  return <article className="panel admin-card"><header><div><strong>{user.displayName||user.username}</strong><code>{user.username} · {user.provider}</code></div><div className="admin-badges">{user.roles.some(role=>role.admin)&&<span className="admin-badge">Admin</span>}{user.mustChangePassword&&<span className="warning-badge">Password change</span>}{!user.enabled&&<span className="error-badge">Disabled</span>}</div></header><div className="admin-form-grid"><label>Display name<input value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label></div><label className="check-label"><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/>Enabled</label><RoleChecks roles={roles} selected={roleIds} onChange={setRoleIds}/><footer><button className="button subtle" disabled={busy} onClick={reset}>Reset password</button><button className="button danger" disabled={busy} onClick={remove}>Delete</button><button className="button primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save user'}</button></footer></article>;
}

function RoleChecks({roles,selected,onChange}:{roles:Role[];selected:number[];onChange:(ids:number[])=>void}){return <fieldset className="admin-checks"><legend>Roles</legend>{roles.map(role=><label className="check-label" key={role.id}><input type="checkbox" checked={selected.includes(role.id)} onChange={event=>onChange(event.target.checked?[...selected,role.id]:selected.filter(id=>id!==role.id))}/>{role.name}{role.admin&&<span className="admin-badge">Admin</span>}</label>)}</fieldset>}

function Roles({roles,changed,failed}:{roles:Role[];changed:()=>Promise<void>;failed:(value:string)=>void}){
  const[name,setName]=useState(''),[description,setDescription]=useState(''),[admin,setAdmin]=useState(false),[busy,setBusy]=useState(false);
  const create=async(event:FormEvent)=>{event.preventDefault();setBusy(true);failed('');try{await api('/admin/roles',{method:'POST',body:JSON.stringify({name,description,admin})});setName('');setDescription('');setAdmin(false);await changed()}catch(error){failed(message(error))}finally{setBusy(false)}};
  return <div className="admin-stack"><form className="panel admin-create" onSubmit={create}><div className="panel-title"><h2>Create role</h2></div><div className="admin-form-grid"><label>Name<input required value={name} onChange={event=>setName(event.target.value)}/></label><label>Description<input value={description} onChange={event=>setDescription(event.target.value)}/></label></div><label className="check-label"><input type="checkbox" checked={admin} onChange={event=>setAdmin(event.target.checked)}/>Administrator role</label><div className="form-actions"><button className="button primary" disabled={busy}>{busy?'Creating…':'Create role'}</button></div></form>{roles.map(role=><RoleEditor key={role.id} role={role} changed={changed} failed={failed}/>)}</div>;
}

function RoleEditor({role,changed,failed}:{role:Role;changed:()=>Promise<void>;failed:(value:string)=>void}){
  const[description,setDescription]=useState(role.description||''),[admin,setAdmin]=useState(role.admin),[grants,setGrants]=useState<DomainGrant[]>(role.grants.map(grant=>({...grant,permissions:[...grant.permissions]}))),[capabilities,setCapabilities]=useState<Capability[]>([...role.capabilities]),[busy,setBusy]=useState(false);
  const updateGrant=(index:number,next:DomainGrant)=>setGrants(grants.map((grant,position)=>position===index?next:grant));
  const save=async()=>{setBusy(true);failed('');try{await api('/admin/roles/'+role.id,{method:'PUT',body:JSON.stringify({description,admin})});await api('/admin/roles/'+role.id+'/grants',{method:'PUT',body:JSON.stringify({grants:grants.filter(grant=>grant.domain&&grant.permissions.length)})});await api('/admin/roles/'+role.id+'/capabilities',{method:'PUT',body:JSON.stringify({capabilities})});await changed()}catch(error){failed(message(error))}finally{setBusy(false)}};
  const remove=async()=>{if(!window.confirm('Delete role '+role.name+'?'))return;setBusy(true);try{await api('/admin/roles/'+role.id,{method:'DELETE'});await changed()}catch(error){failed(message(error))}finally{setBusy(false)}};
  return <article className="panel admin-card"><header><div><strong>{role.name}</strong><code>role:{role.id}</code></div>{role.admin&&<span className="admin-badge">Admin</span>}</header><label>Description<input value={description} onChange={event=>setDescription(event.target.value)}/></label><label className="check-label"><input type="checkbox" checked={admin} onChange={event=>setAdmin(event.target.checked)}/>Administrator role</label><fieldset className="grant-editor"><legend>Domain grants</legend>{grants.map((grant,index)=><div className="grant-row" key={index}><input aria-label={'Grant domain '+(index+1)} placeholder="domain or *" value={grant.domain} onChange={event=>updateGrant(index,{...grant,domain:event.target.value})}/>{(['READ','QUERY','WRITE'] as Permission[]).map(permission=><label className="check-label" key={permission}><input type="checkbox" checked={grant.permissions.includes(permission)} onChange={event=>updateGrant(index,{...grant,permissions:event.target.checked?[...grant.permissions,permission]:grant.permissions.filter(value=>value!==permission)})}/>{permission}</label>)}<button className="icon-button" aria-label="Remove grant" onClick={()=>setGrants(grants.filter((_,position)=>position!==index))}>×</button></div>)}<button className="text-button" onClick={()=>setGrants([...grants,{domain:'',permissions:['READ']}])}>+ Add domain grant</button></fieldset><fieldset className="admin-checks"><legend>Capabilities</legend>{(['VIEW_COMPILED_SQL','VIEW_PHYSICAL_LINEAGE'] as Capability[]).map(capability=><label className="check-label" key={capability}><input type="checkbox" checked={capabilities.includes(capability)} onChange={event=>setCapabilities(event.target.checked?[...capabilities,capability]:capabilities.filter(value=>value!==capability))}/>{capability.replaceAll('_',' ')}</label>)}</fieldset><footer><button className="button danger" disabled={busy} onClick={()=>void remove()}>Delete role</button><button className="button primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save role'}</button></footer></article>;
}

function ServiceAccounts({accounts,roles,changed,failed,reveal}:{accounts:ServiceAccount[];roles:Role[];changed:()=>Promise<void>;failed:(value:string)=>void;reveal:(secret:ServiceSecret)=>void}){
  const[name,setName]=useState(''),[roleId,setRoleId]=useState(roles[0]?.id||0),[busy,setBusy]=useState(false);
  const create=async(event:FormEvent)=>{event.preventDefault();setBusy(true);failed('');try{const secret=await api<ServiceSecret>('/admin/service-accounts',{method:'POST',body:JSON.stringify({name,roleId})});reveal(secret);setName('');await changed()}catch(error){failed(message(error))}finally{setBusy(false)}};
  return <div className="admin-stack"><form className="panel admin-create" onSubmit={create}><div className="panel-title"><h2>Create service account</h2></div><div className="admin-form-grid"><label>Name<input required value={name} onChange={event=>setName(event.target.value)}/></label><label>Role<select value={roleId} onChange={event=>setRoleId(Number(event.target.value))}>{roles.map(role=><option value={role.id} key={role.id}>{role.name}</option>)}</select></label></div><div className="form-actions"><button className="button primary" disabled={busy||!roleId}>{busy?'Creating…':'Create service account'}</button></div></form>{accounts.map(account=><ServiceEditor key={account.id} account={account} roles={roles} changed={changed} failed={failed} reveal={reveal}/>)}</div>;
}

function ServiceEditor({account,roles,changed,failed,reveal}:{account:ServiceAccount;roles:Role[];changed:()=>Promise<void>;failed:(value:string)=>void;reveal:(secret:ServiceSecret)=>void}){
  const[enabled,setEnabled]=useState(account.enabled),[roleId,setRoleId]=useState(account.role.id),[busy,setBusy]=useState(false);
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);failed('');try{await action();await changed()}catch(error){failed(message(error))}finally{setBusy(false)}};
  const rotate=()=>run(async()=>reveal(await api<ServiceSecret>('/admin/service-accounts/'+account.id+'/rotate',{method:'POST'})));
  const remove=()=>{if(window.confirm('Delete service account '+account.name+'?'))void run(()=>api('/admin/service-accounts/'+account.id,{method:'DELETE'}))};
  return <article className="panel admin-card"><header><div><strong>{account.name}</strong><code>service-account:{account.id}</code></div><div className="admin-badges">{account.requiresRotation&&<span className="warning-badge">Rotation required</span>}{!account.enabled&&<span className="error-badge">Disabled</span>}</div></header><div className="admin-form-grid"><label>Role<select value={roleId} onChange={event=>setRoleId(Number(event.target.value))}>{roles.map(role=><option value={role.id} key={role.id}>{role.name}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/>Enabled</label></div><footer><button className="button subtle" disabled={busy} onClick={()=>void rotate()}>Rotate key</button><button className="button danger" disabled={busy} onClick={remove}>Delete</button><button className="button primary" disabled={busy} onClick={()=>void run(()=>api('/admin/service-accounts/'+account.id,{method:'PUT',body:JSON.stringify({roleId,enabled})}))}>Save account</button></footer></article>;
}

function SecretNotice({secret,onClose}:{secret:ServiceSecret;onClose:()=>void}){const[copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard?.writeText(secret.apiKey);setCopied(true)};return <section className="secret-notice" role="status"><div><strong>Copy this key now</strong><p>The plaintext key for <code>{secret.serviceAccount.name}</code> is shown once and cannot be retrieved later.</p><code className="secret-value">{secret.apiKey}</code></div><button className="button subtle" onClick={()=>void copy()}>{copied?'Copied':'Copy key'}</button><button className="button primary" onClick={onClose}>I saved it</button></section>}
function AdminState({title,body}:{title:string;body:string}){return <div className="state-card"><strong>{title}</strong><small>{body}</small></div>}
function message(error:unknown){if(error instanceof ApiError&&error.status===409)return error.message;if(error instanceof Error)return error.message;return 'The administration request failed.'}
